### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/typescript-tslint-plugin#1]
## typescript-tslint-plugin (node-module)
- [x] Publish repository @mjbvz 
- [x] Publish npm module @mjbvz 
- [x] Surface TSLint warnings to user (first line of file?) @mjbvz 

## tslint-language-service (node module) - old plugin implementation
- [x] PR against https://github.com/angelozerr/tslint-language-service that explains that the project continues in typescript-tslint-plugin @mjbvz @egamma 

## vscode-typescript-tstlint-plugin (extension)
https://github.com/Microsoft/vscode-typescript-tslint-plugin

- [x] Create separate repo for vscode extension: vscode-tslint-ts-plugin: @mjbvz 
- [x] Help users migrate from using vscode tslint settings to using settings in tsconfig.json @mjbvz 
- [x] Add schema and problem matcher contributions @mjbvz 
- [ ] Add "open tslint file" command @mjbvz 
- [ ] Command to create a tslint.json @mjbvz 
- [x] Publish extension to the market place @mjbvz 
- [x] Fix on save: @mjbvz Explore

## vscode-tslint (extension) 
- [x] Migration guidance from old tslint extension to new one: @egamma October, depends on having new repos setup first

## vscode-ts-tslint (extension)
- [x] Add deprecation message @egamma October, depends on having  new repos setup first
- [ ] Unpublish from market place @egamma

## Not for October
- [ ] Fix all should handle overlapping fixes [issue](https://github.com/Microsoft/vscode-tslint/issues/382)
- [ ] Task provider to run tslint in a folder

**Comment by mjbvz** [comment]
Closing this as most of the items have been accomplished and the few missing features have feature requests tracking them
